name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PR_LABELS_JSON: ${{ toJson(github.event.pull_request.labels) }}
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo "PR Labels"
          echo "PR_LABELS_JSON=${PR_LABELS_JSON}"
